package com.vega.protocol.constant;

public enum AccountType {
    INSURANCE,
    GLOBAL_INSURANCE,
    SETTLEMENT,
    MARGIN,
    GENERAL,
    FEES_INFRASTRUCTURE,
    FEES_LIQUIDITY,
    FEES_MAKER,
    LOCK_WITHDRAW,
    BOND,
    EXTERNAL,
    GLOBAL_REWARD,
    PENDING_TRANSFERS,
    REWARD_TAKER_PAID_FEES,
    REWARD_MAKER_PAID_FEES,
    REWARD_MAKER_RECEIVED_FEES,
    REWARD_LP_RECEIVED_FEES,
    REWARD_MARKET_PROPOSERS
}